# Generated by Django 5.1 on 2025-06-08 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_system_device_system'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='devices.system')),
            ],
            options={
                'unique_together': {('name', 'system')},
            },
        ),
        migrations.AddField(
            model_name='device',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='devices.unit'),
        ),
    ]
