# Generated by Django 5.1 on 2025-06-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_unit_device_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='thingsboard_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
