# Generated by Django 5.1 on 2026-04-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_device_thingsboard_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayIOT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('base_url', models.URLField(help_text='Ex: http://thingsboard:8080')),
                ('mqtt_port', models.PositiveIntegerField(default=1883)),
                ('mqtt_keep_alive', models.PositiveIntegerField(default=60)),
                ('auth_method', models.CharField(choices=[('user_password', 'Usuario e senha'), ('api_key', 'API Key')], default='user_password', max_length=32)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('api_key', models.CharField(blank=True, max_length=512, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
    ]
